language: python
python:
- '3.6'
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b"
- export PATH=~/miniconda3/bin/:$PATH
- # some configuration to make it easy to install things
- conda config --set always_yes yes --set changeps1 no
- conda update --yes conda
install:
- conda create -n testenv --yes python=$TRAVIS_PYTHON_VERSION pip
- source activate testenv
- make conda_install
before_script:
- git config --global user.email "olga.botvinnik@gmail.com"
- git config --global user.name "olgabot"
- git config --global push.default simple
- export REPO_URL_GITHUB="https://$GH_TOKEN@github.com/$GH_REPO.git"
script:
- make coverage
- make lint
after_script:
- pip install codecov
- codecov
deploy:
  provider: pypi
  on:
    tags: true
    repo: olgabot/aguamenti
env:
  global:
  - secure: DuIt34ItClj+dYW36XaQZjq0e8WXx3fmr0C7qt/LDlefK/7OmAub6DF9zaKpyb6zKPO9N5ygGrEs+nBEBx1ZsoQKOCpLJ3jiMw+kgoyH/+x7Nw1W4DJKGMxTietxBZXkWfNJyY83ILGSM3qqr6U3TcVpnDSy2TTHlpmvb3P1bt0uqwrUkaA/czjij2r6mgougRglmGDFMu5nm0nIufzE4vZzSjJzFZrLwoTmwvnX20vrCX/IxkNaeAv7P5UXyjeYAP7v70O3e2irpCscP+5IuiMo9cDMDaiLxjwZW1htpMUfNQ14uiO+hxxNELHBD68tqC3vuK2aEL2ARmhCdQSqfgLLsMTS97gllXau0MdFWMnt886NrnR3M3VDXM2a1JwkZs8E+1vKVdTz1TiqYr/DH3BGJ/2MmhEqU48/S3rHBitKfpe73QcCAGn7iTQZbPeVZLcm5xLjGmKW391Q4TM6d/jaTUz82xGogdMfvlaYPZnLfPV3g5XWx2kAs2RwpSuTUcti4dxnkAguXwKkQGbIPT2JMIZ6ZIbos2vKMp6+e821gQ+LTSduSAT7wasEphwqAsl1q0Y0AUKovhaz40R6FRsJ73V5ktpaI2Pt9P8qsrf3Ip9p1I1cC664/c6xWyEO6iJ+u6hH0AB6x0wgl9bN/p1iovig9dptHn2BPJtmiVU=
  - secure: KdhXCJIcYfCZGRFpO50cz2z/bfxnDB5MFsBfPc4hIyhih1aJNKBk1DJ7D8ByHcO4OF4f1Gy/Sl3W2hBXPoR1IkftvQg/CbpMK1xEX61mzMKqaQA19XC1e4DDqQIvtQX/wTmzRsPfwMKLpKoLLEuSlUJJf6k6QqSOEbo7NSFb7nnhwDtLmq4a4jjaj7qgGxeib1EgEaRenxVDzoYGXyKRkQJPG7D0amLil4fqwHazjPRQFcGwFEum6f6os32TDARpKZDJheqekAL2dVqjW3MCgZjQ5/U359wVaoYrdTmPkBkTFsZIhduzTOkk9c/HaafocI7sOXzpKZ8no1aCBeGEpvxQl+TSkCyTzbZlyQ8DGEV76pvibuG4h9aEbBL+r7FQFRZi6dYt6qZl/f+UR0APAhmCED1MabmulivrRVsVgBu5dLFLJ4Av2ARqj1gnXH4VngGraiw7c+sgprBMetT9nwH55/wCkLcoLsIqiSCE0iFTdr4GGyKs0SrMQCe4/ShOuWT09csZZa8twDWX5wiwM35YBcltgSpLFtKffThRymiJ1QmgmIZ9zOq/orrfLw40GQsaDL8j9Kz2soHnAFM0DsltnOQQ3rB1/Jvh+Npk5L9JdkFcwJdiqtwVOInI2nd6ISR7b2vLNFGdGMaXUIVC78dM3VYLCaOjxkiOpoyfm+Q=
